[2025-07-25T04:20:14.317+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-25T04:20:14.343+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bank_data_pipeline.risk_alerts_2 manual__2025-07-25T04:20:09.049443+00:00 [queued]>
[2025-07-25T04:20:14.349+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bank_data_pipeline.risk_alerts_2 manual__2025-07-25T04:20:09.049443+00:00 [queued]>
[2025-07-25T04:20:14.349+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-07-25T04:20:14.360+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): risk_alerts_2> on 2025-07-25 04:20:09.049443+00:00
[2025-07-25T04:20:14.366+0000] {standard_task_runner.py:63} INFO - Started process 681 to run task
[2025-07-25T04:20:14.369+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'bank_data_pipeline', 'risk_alerts_2', 'manual__2025-07-25T04:20:09.049443+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/bank_data_pipeline.py', '--cfg-path', '/tmp/tmpl2dmzg28']
[2025-07-25T04:20:14.370+0000] {standard_task_runner.py:91} INFO - Job 24: Subtask risk_alerts_2
[2025-07-25T04:20:14.384+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-25T04:20:14.418+0000] {task_command.py:426} INFO - Running <TaskInstance: bank_data_pipeline.risk_alerts_2 manual__2025-07-25T04:20:09.049443+00:00 [running]> on host f91aa71dc96e
[2025-07-25T04:20:14.506+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineering_team_2' AIRFLOW_CTX_DAG_ID='bank_data_pipeline' AIRFLOW_CTX_TASK_ID='risk_alerts_2' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T04:20:09.049443+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-25T04:20:09.049443+00:00'
[2025-07-25T04:20:14.507+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-25T04:20:14.518+0000] {bank_data_pipeline.py:168} INFO - Starting risk alert checks for run manual__2025-07-25T04:20:09.049443+00:00
[2025-07-25T04:20:14.752+0000] {bank_data_pipeline.py:189} INFO - Risk alert checks passed: Risk violations: 36

[2025-07-25T04:20:14.752+0000] {bank_data_pipeline.py:190} INFO - Task completed successfully
[2025-07-25T04:20:14.752+0000] {python.py:237} INFO - Done. Returned value was: {'status': 'success', 'message': 'Risk alert checks passed'}
[2025-07-25T04:20:14.753+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-25T04:20:14.773+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=bank_data_pipeline, task_id=risk_alerts_2, run_id=manual__2025-07-25T04:20:09.049443+00:00, execution_date=20250725T042009, start_date=20250725T042014, end_date=20250725T042014
[2025-07-25T04:20:14.825+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-25T04:20:14.848+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-25T04:20:14.851+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
