[2025-07-25T04:18:00.253+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-25T04:18:00.278+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bank_data_pipeline.risk_alerts_2 manual__2025-07-25T04:17:56.965555+00:00 [queued]>
[2025-07-25T04:18:00.284+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bank_data_pipeline.risk_alerts_2 manual__2025-07-25T04:17:56.965555+00:00 [queued]>
[2025-07-25T04:18:00.285+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-07-25T04:18:00.295+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): risk_alerts_2> on 2025-07-25 04:17:56.965555+00:00
[2025-07-25T04:18:00.300+0000] {standard_task_runner.py:63} INFO - Started process 628 to run task
[2025-07-25T04:18:00.304+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'bank_data_pipeline', 'risk_alerts_2', 'manual__2025-07-25T04:17:56.965555+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/bank_data_pipeline.py', '--cfg-path', '/tmp/tmpuah30uea']
[2025-07-25T04:18:00.305+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask risk_alerts_2
[2025-07-25T04:18:00.319+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-25T04:18:00.345+0000] {task_command.py:426} INFO - Running <TaskInstance: bank_data_pipeline.risk_alerts_2 manual__2025-07-25T04:17:56.965555+00:00 [running]> on host f91aa71dc96e
[2025-07-25T04:18:00.416+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineering_team_2' AIRFLOW_CTX_DAG_ID='bank_data_pipeline' AIRFLOW_CTX_TASK_ID='risk_alerts_2' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T04:17:56.965555+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-25T04:17:56.965555+00:00'
[2025-07-25T04:18:00.417+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-25T04:18:00.428+0000] {bank_data_pipeline.py:168} INFO - Starting risk alert checks for run manual__2025-07-25T04:17:56.965555+00:00
[2025-07-25T04:18:00.666+0000] {bank_data_pipeline.py:189} INFO - Risk alert checks passed: Risk violations: 36

[2025-07-25T04:18:00.666+0000] {bank_data_pipeline.py:190} INFO - Task completed successfully
[2025-07-25T04:18:00.667+0000] {python.py:237} INFO - Done. Returned value was: {'status': 'success', 'message': 'Risk alert checks passed'}
[2025-07-25T04:18:00.667+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-25T04:18:00.703+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=bank_data_pipeline, task_id=risk_alerts_2, run_id=manual__2025-07-25T04:17:56.965555+00:00, execution_date=20250725T041756, start_date=20250725T041800, end_date=20250725T041800
[2025-07-25T04:18:00.759+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-25T04:18:00.782+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-25T04:18:00.785+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
